# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\MyMoney5JO\database\CarRecSys (2).ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CarInfo(object):
    def setupUi(self, CarInfo):
        CarInfo.setObjectName("CarInfo")
        CarInfo.resize(808, 260)
        CarInfo.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.verticalLayoutWidget = QtWidgets.QWidget(CarInfo)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 372, 202))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNum.setMinimumSize(QtCore.QSize(370, 200))
        self.lblNum.setMaximumSize(QtCore.QSize(250, 400))
        self.lblNum.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.lblNum.setText("")
        self.lblNum.setObjectName("lblNum")
        self.verticalLayout.addWidget(self.lblNum)
        self.btn_loadFromFile = QtWidgets.QPushButton(CarInfo)
        self.btn_loadFromFile.setGeometry(QtCore.QRect(290, 220, 93, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_loadFromFile.setPalette(palette)
        self.btn_loadFromFile.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.btn_loadFromFile.setObjectName("btn_loadFromFile")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(CarInfo)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(390, 10, 411, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblcarinfo = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblcarinfo.setObjectName("tblcarinfo")
        self.tblcarinfo.setColumnCount(0)
        self.tblcarinfo.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tblcarinfo)

        self.retranslateUi(CarInfo)
        QtCore.QMetaObject.connectSlotsByName(CarInfo)

    def retranslateUi(self, CarInfo):
        _translate = QtCore.QCoreApplication.translate
        CarInfo.setWindowTitle(_translate("CarInfo", "차량정보 인식 시스템"))
        self.btn_loadFromFile.setText(_translate("CarInfo", "PushButton"))
